
# Open this project on vscode on docker remote
# with importing "docker-compose.yaml", not this one .
# This fils is just for reminder of commands.
RUN yum upgrade
# setting for building yesod project or some.
RUN yum install zlib-devel

RUN yum install openssl-devel
RUN yum install libgcrypt-devel

RUN export LC_ALL=en_US.UTF-8

# update gcc 7

RUN yum install centos-release-scl
RUN yum-config-manager --enable rhel-server-rhscl-7-rpms
RUN yum install devtoolset-7
RUN source scl_source enable devtoolset-7
# write $HOME/.bashrc above command.
RUN gcc -v



# setting stack and cabal 
RUN curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
RUN ghcup install ghc 8.10.4
RUN ghcup set ghc 8.10.4

# for error happen.
# RUN yum install ncurses-devel
RUN yum install gmp gmp-devel 
# 
# install nodejs
RUN curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install nodejs -y

# for using sqlite 
RUN yum install postgresql-devel

# dependecies
RUN yum install bzip2
RUN yum -y install fontconfig-devel
# add phantom-js
RUN curl -sLO https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar -jxvf phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN phantomjs-2.1.1-linux-x86_64/bin/
RUN chmod +x phantomjs
# add path ~~~
# RUN cd ..
# RUN cd ..
RUN mv phantomjs-2.1.1-linux-x86_64 /root
RUN echo "export PATH=root/phantomjs-2.1.1-linux-x86_64/bin:$PATH" >> /root/.bashrc
# finish 

# Start haskell project
# stack install implicit-hie
EXPOSE 3000


