name:                serverScotty
version:             0.1.0.0
github:              "githubuser/serverScotty"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/serverScotty#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- http-types
- resourcet
- scotty
- text
- bytestring
- blaze-html
- persistent
- persistent-template
- persistent-sqlite
- persistent-postgresql
- esqueleto
- monad-logger
- heroku
- transformers
- wai-middleware-static
- wai-extra
- time
- parsec
- HUnit
- silently
- test-framework
- test-framework-hunit

library:
  source-dirs: src

executables:
  serverScotty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - serverScotty

tests:
  serverScotty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - serverScotty
